### ISSUE TITLE
xml转换成excel摘要，预置条件，步骤和预期结果是否可以加上序号?

### ISSUE THREAD

**Issue by ro9963** [yaitza/TestLinkConverter#16]
作者你好，我关注你一段时间了，找了这么多工具就你这个是最好用的。目前我们工作项目中的转换工具就是用你这个。
有个问题看看能否解决？--我们导出的xml转换成excel，在web上面显示的带有序号（直接在testlink上面的辅助栏选择的序号，不是人工写的序号）那些都没有转换出来，上下两个都合在一起了，导致读写困难，这个问题是否可以解决的？
![screenshot](https://user-images.githubusercontent.com/49099182/67059710-b7a0e080-f18c-11e9-870a-deb95a185b6e.png)

**Comment by yaitza** [comment]
你好，你的意思是在xml导出excel的时候，需要把测试步骤以及预期结果的步骤序号带上么？


如果是我上面描述的功能，应该很好解决；我这边尽快按照你的要求完成相关开发。




 




------------------ 原始邮件 ------------------
发件人: "ro9963"<notifications@github.com>;
发送时间: 2019年10月18日(星期五) 上午9:50
收件人: "yaitza/TestLinkConverter"<TestLinkConverter@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [yaitza/TestLinkConverter] xml转换成excel摘要，预置条件，步骤和预期结果是否可以加上序号? (#16)




作者你好，我关注你一段时间了，找了这么多工具就你这个是最好用的。目前我们工作项目中的转换工具就是用你这个。
 有个问题看看能否解决？--我们导出的xml转换成excel，在web上面显示的带有序号（直接在testlink上面的辅助栏选择的序号，不是人工写的序号）那些都没有转换出来，上下两个都合在一起了，导致读写困难，这个问题是否可以解决的？

**Comment by yaitza** [comment]
你是希望看到这个样子么？







 




------------------ 原始邮件 ------------------
发件人: "海道"<yaitza@foxmail.com>;
发送时间: 2019年10月18日(星期五) 上午9:54
收件人: "yaitza/TestLinkConverter"<reply@reply.github.com>;

主题: 回复：[yaitza/TestLinkConverter] xml转换成excel摘要，预置条件，步骤和预期结果是否可以加上序号? (#16)



你好，你的意思是在xml导出excel的时候，需要把测试步骤以及预期结果的步骤序号带上么？


如果是我上面描述的功能，应该很好解决；我这边尽快按照你的要求完成相关开发。




 




------------------ 原始邮件 ------------------
发件人: "ro9963"<notifications@github.com>;
发送时间: 2019年10月18日(星期五) 上午9:50
收件人: "yaitza/TestLinkConverter"<TestLinkConverter@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [yaitza/TestLinkConverter] xml转换成excel摘要，预置条件，步骤和预期结果是否可以加上序号? (#16)




作者你好，我关注你一段时间了，找了这么多工具就你这个是最好用的。目前我们工作项目中的转换工具就是用你这个。
 有个问题看看能否解决？--我们导出的xml转换成excel，在web上面显示的带有序号（直接在testlink上面的辅助栏选择的序号，不是人工写的序号）那些都没有转换出来，上下两个都合在一起了，导致读写困难，这个问题是否可以解决的？

**Comment by ro9963** [comment]
谢谢回复，是的，因为我们这边转换成excel的文件是要给到客户，所以希望界面描述清晰。目前我们是用工具转换后，自己整理的，最终效果如下：
![QQ截图20191018181342](https://user-images.githubusercontent.com/49099182/67086312-0a9d8680-f1d3-11e9-8309-6c2a8a3721c7.png)

对应testlink的原始内容是这样的：
![QQ截图](https://user-images.githubusercontent.com/49099182/67086515-85ff3800-f1d3-11e9-8754-3bc195ce0582.png)

**Comment by ro9963** [comment]
个人在使用过程中的一点小建议：
1、摘要和预置条件，例如用例中，有多个序号或者预置条件的，可以添加序号，目前的实现方式是没有在每行之间区别开来的
![1](https://user-images.githubusercontent.com/49099182/67086911-6c122500-f1d4-11e9-8672-46f381e4a65d.png)
![2](https://user-images.githubusercontent.com/49099182/67086915-6ddbe880-f1d4-11e9-9d11-954fc94b61e7.png)
2、操作步骤与期望结果，如果用例只有一个少量步骤，这样如果有大量用例一起导出，excel表上面很难区分这个步骤是对应的哪个用例，如下：
![3](https://user-images.githubusercontent.com/49099182/67087174-f78bb600-f1d4-11e9-9e18-00bb4af3d524.png)

**Comment by yaitza** [comment]
测试步骤以及预期结果已添加测试序号，不过考虑到其他人使用可能会在一个步骤里面写多个步骤，故该功能可配置。

**Comment by ro9963** [comment]
非常感谢！！还有个小疑问，摘要和预置条件能否也一起加上序号？我下载试了一下，步骤和期望结果已经可以了，摘要和预置条件还是没有序号的。
----- 原始邮件 -----
发件人：yaitza <notifications@github.com>
收件人：yaitza/TestLinkConverter <TestLinkConverter@noreply.github.com>
抄送人：ro9963 <ro9963@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[yaitza/TestLinkConverter]_xml转换成excel摘要，预置条件，步骤和预期结果是否可以加上序号?_(#16)
日期：2019年10月21日 17点55分

测试步骤以及预期结果已添加测试序号，不过考虑到其他人使用可能会在一个步骤里面写多个步骤，故该功能可配置。

**Comment by yaitza** [comment]
你好，如果要把预置条件和摘要也加上序号，我需要知道你们对应xml的格式是什么样子的。因为testlink本身是不支持预置条件和摘要是没有步骤区分的。

**Comment by ro9963** [comment]
预置条件这里可能理解成编号更容易理解，例如我预置条件有好几个，这样就用1、2、3列出来，附件是在testlink 1.9.19导出来的测试用例，在界面显示如下：

----- 原始邮件 -----
发件人：yaitza <notifications@github.com>
收件人：yaitza/TestLinkConverter <TestLinkConverter@noreply.github.com>
抄送人：ro9963 <ro9963@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[yaitza/TestLinkConverter]_xml转换成excel摘要，预置条件，步骤和预期结果是否可以加上序号?_(#16)
日期：2019年10月22日 09点40分

你好，如果要把预置条件和摘要也加上序号，我需要知道你们对应xml的格式是什么样子的。因为testlink本身是不支持预置条件和摘要是没有步骤区分的。
